apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: fleet-demo
    tier: frontend
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 80
  selector:
    app: fleet-demo
    tier: frontend
